- hosts: all
  become: yes
  user: thiago
  gather_gacts: no
  pre_tasks:
  - name: 'Atualização de repositórios'
    raw: 'yum update'
  - name: 'Install python'
    raw: 'yum install python'
  roles:
  - { role: install-k8s, tags: ["install_k8s_role"] }

- hosts: k8s-master
  become: yes
  user: thiago
  roles:
  - { role: create-cluster, tags: ["create_cluster_role"] }

- hosts: k8s-worker
  become: yes
  user: thiago
  roles:
  - { role: join-workers, tags: ["join_workers_role"] }